package com.santiago.biblioteca.bean;
// Generated 06/11/2013 04:56:16 AM by Hibernate Tools 3.6.0


import java.util.HashSet;
import java.util.Set;
import javax.persistence.Column;
import javax.persistence.Entity;
import javax.persistence.FetchType;
import javax.persistence.Id;
import javax.persistence.JoinColumn;
import javax.persistence.ManyToOne;
import javax.persistence.OneToMany;
import javax.persistence.Table;

/**
 * Ejemplar generated by hbm2java
 */
@Entity
@Table(name="ejemplar"
    ,catalog="biblioteca"
)
public class Ejemplar  implements java.io.Serializable {


     private int id;
     private Libro libro;
     private String localizacion;
     private Integer anno;
     private Integer estado;
     private Set prestamos = new HashSet(0);
     private Set reservas = new HashSet(0);

    public Ejemplar() {
    }

	
    public Ejemplar(int id, Libro libro) {
        this.id = id;
        this.libro = libro;
    }
    public Ejemplar(int id, Libro libro, String localizacion, Integer anno, Integer estado, Set prestamos, Set reservas) {
       this.id = id;
       this.libro = libro;
       this.localizacion = localizacion;
       this.anno = anno;
       this.estado = estado;
       this.prestamos = prestamos;
       this.reservas = reservas;
    }
   
     @Id 

    
    @Column(name="id", unique=true, nullable=false)
    public int getId() {
        return this.id;
    }
    
    public void setId(int id) {
        this.id = id;
    }

@ManyToOne(fetch=FetchType.LAZY)
    @JoinColumn(name="libros_id", nullable=false)
    public Libro getLibro() {
        return this.libro;
    }
    
    public void setLibro(Libro libro) {
        this.libro = libro;
    }

    
    @Column(name="localizacion", length=45)
    public String getLocalizacion() {
        return this.localizacion;
    }
    
    public void setLocalizacion(String localizacion) {
        this.localizacion = localizacion;
    }

    
    @Column(name="anno")
    public Integer getAnno() {
        return this.anno;
    }
    
    public void setAnno(Integer anno) {
        this.anno = anno;
    }

    
    @Column(name="estado")
    public Integer getEstado() {
        return this.estado;
    }
    
    public void setEstado(Integer estado) {
        this.estado = estado;
    }

@OneToMany(fetch=FetchType.LAZY, mappedBy="ejemplar")
    public Set getPrestamos() {
        return this.prestamos;
    }
    
    public void setPrestamos(Set prestamos) {
        this.prestamos = prestamos;
    }

@OneToMany(fetch=FetchType.LAZY, mappedBy="ejemplar")
    public Set getReservas() {
        return this.reservas;
    }
    
    public void setReservas(Set reservas) {
        this.reservas = reservas;
    }




}


