package com.santiago.biblioteca.bean;
// Generated 06/11/2013 04:56:16 AM by Hibernate Tools 3.6.0

import java.util.HashSet;
import java.util.Set;
import javax.persistence.Column;
import javax.persistence.Entity;
import javax.persistence.FetchType;
import javax.persistence.GeneratedValue;
import static javax.persistence.GenerationType.IDENTITY;
import javax.persistence.Id;
import javax.persistence.JoinColumn;
import javax.persistence.ManyToOne;
import javax.persistence.OneToMany;
import javax.persistence.Table;

/**
 * Libro generated by hbm2java
 */
@Entity
@Table(name = "libro", catalog = "biblioteca"
)
public class Libro implements java.io.Serializable {

    private int id;
    private Autor autor;
    private String isbn;
    private String titulo;
    private String editorial;
    private Integer numeropag;
    private Set ejemplars = new HashSet(0);

    public Libro() {
    }

    public Libro(int id, Autor autor) {
        this.id = id;
        this.autor = autor;
    }

    public Libro(int id, Autor autor, String isbn, String titulo, String editorial, Integer numeropag, Set ejemplars) {
        this.id = id;
        this.autor = autor;
        this.isbn = isbn;
        this.titulo = titulo;
        this.editorial = editorial;
        this.numeropag = numeropag;
        this.ejemplars = ejemplars;
    }

    @Id
    @GeneratedValue(strategy = IDENTITY)

    @Column(name = "id", unique = true, nullable = false)
    public int getId() {
        return this.id;
    }

    public void setId(int id) {
        this.id = id;
    }

    @ManyToOne(fetch = FetchType.LAZY)
    @JoinColumn(name = "autor_id", nullable = false)
    public Autor getAutor() {
        return this.autor;
    }

    public void setAutor(Autor autor) {
        this.autor = autor;
    }

    @Column(name = "isbn", length = 45)
    public String getIsbn() {
        return this.isbn;
    }

    public void setIsbn(String isbn) {
        this.isbn = isbn;
    }

    @Column(name = "titulo", length = 45)
    public String getTitulo() {
        return this.titulo;
    }

    public void setTitulo(String titulo) {
        this.titulo = titulo;
    }

    @Column(name = "editorial", length = 45)
    public String getEditorial() {
        return this.editorial;
    }

    public void setEditorial(String editorial) {
        this.editorial = editorial;
    }

    @Column(name = "numeropag")
    public Integer getNumeropag() {
        return this.numeropag;
    }

    public void setNumeropag(Integer numeropag) {
        this.numeropag = numeropag;
    }

//@OneToMany(fetch=FetchType.LAZY, mappedBy="libro")
//    public Set getEjemplars() {
//        return this.ejemplars;
//    }
//    
//    public void setEjemplars(Set ejemplars) {
//        this.ejemplars = ejemplars;
//    }
}
