package com.santiago.biblioteca.bean;
// Generated 06/11/2013 04:56:16 AM by Hibernate Tools 3.6.0


import javax.persistence.Column;
import javax.persistence.Entity;
import javax.persistence.FetchType;
import javax.persistence.Id;
import javax.persistence.JoinColumn;
import javax.persistence.ManyToOne;
import javax.persistence.Table;

/**
 * Multa generated by hbm2java
 */
@Entity
@Table(name="multa"
    ,catalog="biblioteca"
)
public class Multa  implements java.io.Serializable {


     private int id;
     private Prestamo prestamo;
     private Double monto;
     private Integer diasTarde;

    public Multa() {
    }

	
    public Multa(int id, Prestamo prestamo) {
        this.id = id;
        this.prestamo = prestamo;
    }
    public Multa(int id, Prestamo prestamo, Double monto, Integer diasTarde) {
       this.id = id;
       this.prestamo = prestamo;
       this.monto = monto;
       this.diasTarde = diasTarde;
    }
   
     @Id 

    
    @Column(name="id", unique=true, nullable=false)
    public int getId() {
        return this.id;
    }
    
    public void setId(int id) {
        this.id = id;
    }

@ManyToOne(fetch=FetchType.LAZY)
    @JoinColumn(name="prestamos_id", nullable=false)
    public Prestamo getPrestamo() {
        return this.prestamo;
    }
    
    public void setPrestamo(Prestamo prestamo) {
        this.prestamo = prestamo;
    }

    
    @Column(name="monto", precision=10)
    public Double getMonto() {
        return this.monto;
    }
    
    public void setMonto(Double monto) {
        this.monto = monto;
    }

    
    @Column(name="diasTarde")
    public Integer getDiasTarde() {
        return this.diasTarde;
    }
    
    public void setDiasTarde(Integer diasTarde) {
        this.diasTarde = diasTarde;
    }




}


