package com.santiago.biblioteca.bean;
// Generated 06/11/2013 04:56:16 AM by Hibernate Tools 3.6.0

import java.util.Date;
import java.util.HashSet;
import java.util.Set;
import javax.persistence.Column;
import javax.persistence.Entity;
import javax.persistence.FetchType;
import javax.persistence.GeneratedValue;
import static javax.persistence.GenerationType.IDENTITY;
import javax.persistence.Id;
import javax.persistence.JoinColumn;
import javax.persistence.ManyToOne;
import javax.persistence.Table;
import javax.persistence.Temporal;
import javax.persistence.TemporalType;

/**
 * Prestamo generated by hbm2java
 */
@Entity
@Table(name = "prestamo", catalog = "biblioteca"
)
public class Prestamo implements java.io.Serializable {

    private int id;
    private Usuario usuario;
    private Ejemplar ejemplar;
    private Publicacion publicacion;
    private Double montoMulta;
    private Date fechaInicio;
    private Date fechaFin;
    private Date fechaDevolucion;
    private String estado;
    private Set multas = new HashSet(0);

    public Prestamo() {
    }

    public Prestamo(int id, Usuario usuario) {
        this.id = id;
        this.usuario = usuario;
    }

    public Prestamo(int id, Usuario usuario, Ejemplar ejemplar, Publicacion publicacion, Double montoMulta, Date fechaInicio, Date fechaFin, Date fechaDevolucion, String estado, Set multas) {
        this.id = id;
        this.usuario = usuario;
        this.ejemplar = ejemplar;
        this.publicacion = publicacion;
        this.montoMulta = montoMulta;
        this.fechaInicio = fechaInicio;
        this.fechaFin = fechaFin;
        this.fechaDevolucion = fechaDevolucion;
        this.estado = estado;
        this.multas = multas;
    }

    @Id
    @GeneratedValue(strategy = IDENTITY)

    @Column(name = "id", unique = true, nullable = false)
    public int getId() {
        return this.id;
    }

    public void setId(int id) {
        this.id = id;
    }

    @ManyToOne(fetch = FetchType.LAZY)
    @JoinColumn(name = "usuario_id", nullable = false)
    public Usuario getUsuario() {
        return this.usuario;
    }

    public void setUsuario(Usuario usuario) {
        this.usuario = usuario;
    }

    @ManyToOne(fetch = FetchType.LAZY)
    @JoinColumn(name = "ejemplar_id")
    public Ejemplar getEjemplar() {
        return this.ejemplar;
    }

    public void setEjemplar(Ejemplar ejemplar) {
        this.ejemplar = ejemplar;
    }

    @ManyToOne(fetch = FetchType.LAZY)
    @JoinColumn(name = "publicacion_id")
    public Publicacion getPublicacion() {
        return this.publicacion;
    }

    public void setPublicacion(Publicacion publicacion) {
        this.publicacion = publicacion;
    }

    @Column(name = "montoMulta", precision = 7)
    public Double getMontoMulta() {
        return this.montoMulta;
    }

    public void setMontoMulta(Double montoMulta) {
        this.montoMulta = montoMulta;
    }

    @Temporal(TemporalType.DATE)
    @Column(name = "fechaInicio", length = 10)
    public Date getFechaInicio() {
        return this.fechaInicio;
    }

    public void setFechaInicio(Date fechaInicio) {
        this.fechaInicio = fechaInicio;
    }

    @Temporal(TemporalType.DATE)
    @Column(name = "fechaFin", length = 10)
    public Date getFechaFin() {
        return this.fechaFin;
    }

    public void setFechaFin(Date fechaFin) {
        this.fechaFin = fechaFin;
    }

    @Temporal(TemporalType.DATE)
    @Column(name = "fechaDevolucion", length = 10)
    public Date getFechaDevolucion() {
        return this.fechaDevolucion;
    }

    public void setFechaDevolucion(Date fechaDevolucion) {
        this.fechaDevolucion = fechaDevolucion;
    }

    @Column(name = "estado", length = 45)
    public String getEstado() {
        return this.estado;
    }

    public void setEstado(String estado) {
        this.estado = estado;
    }
//
//@OneToMany(fetch=FetchType.LAZY, mappedBy="prestamo")
//    public Set getMultas() {
//        return this.multas;
//    }
//    
//    public void setMultas(Set multas) {
//        this.multas = multas;
//    }

}
