package com.santiago.biblioteca.bean;
// Generated 06/11/2013 04:56:16 AM by Hibernate Tools 3.6.0


import java.util.Date;
import java.util.HashSet;
import java.util.Set;
import javax.persistence.Column;
import javax.persistence.Entity;
import javax.persistence.FetchType;
import javax.persistence.Id;
import javax.persistence.JoinColumn;
import javax.persistence.ManyToOne;
import javax.persistence.OneToMany;
import javax.persistence.Table;
import javax.persistence.Temporal;
import javax.persistence.TemporalType;

/**
 * Publicacion generated by hbm2java
 */
@Entity
@Table(name="publicacion"
    ,catalog="biblioteca"
)
public class Publicacion  implements java.io.Serializable {


     private int id;
     private Tipopublicacion tipopublicacion;
     private String titulo;
     private String subtitulo;
     private String editor;
     private Integer numero;
     private Date fechaEdicion;
     private Set reservas = new HashSet(0);
     private Set prestamos = new HashSet(0);

    public Publicacion() {
    }

	
    public Publicacion(int id, Tipopublicacion tipopublicacion) {
        this.id = id;
        this.tipopublicacion = tipopublicacion;
    }
    public Publicacion(int id, Tipopublicacion tipopublicacion, String titulo, String subtitulo, String editor, Integer numero, Date fechaEdicion, Set reservas, Set prestamos) {
       this.id = id;
       this.tipopublicacion = tipopublicacion;
       this.titulo = titulo;
       this.subtitulo = subtitulo;
       this.editor = editor;
       this.numero = numero;
       this.fechaEdicion = fechaEdicion;
       this.reservas = reservas;
       this.prestamos = prestamos;
    }
   
     @Id 

    
    @Column(name="id", unique=true, nullable=false)
    public int getId() {
        return this.id;
    }
    
    public void setId(int id) {
        this.id = id;
    }

@ManyToOne(fetch=FetchType.LAZY)
    @JoinColumn(name="tipopublicacion_id", nullable=false)
    public Tipopublicacion getTipopublicacion() {
        return this.tipopublicacion;
    }
    
    public void setTipopublicacion(Tipopublicacion tipopublicacion) {
        this.tipopublicacion = tipopublicacion;
    }

    
    @Column(name="titulo", length=45)
    public String getTitulo() {
        return this.titulo;
    }
    
    public void setTitulo(String titulo) {
        this.titulo = titulo;
    }

    
    @Column(name="subtitulo", length=45)
    public String getSubtitulo() {
        return this.subtitulo;
    }
    
    public void setSubtitulo(String subtitulo) {
        this.subtitulo = subtitulo;
    }

    
    @Column(name="editor", length=45)
    public String getEditor() {
        return this.editor;
    }
    
    public void setEditor(String editor) {
        this.editor = editor;
    }

    
    @Column(name="numero")
    public Integer getNumero() {
        return this.numero;
    }
    
    public void setNumero(Integer numero) {
        this.numero = numero;
    }

    @Temporal(TemporalType.DATE)
    @Column(name="fechaEdicion", length=10)
    public Date getFechaEdicion() {
        return this.fechaEdicion;
    }
    
    public void setFechaEdicion(Date fechaEdicion) {
        this.fechaEdicion = fechaEdicion;
    }

//@OneToMany(fetch=FetchType.LAZY, mappedBy="publicacion")
//    public Set getReservas() {
//        return this.reservas;
//    }
//    
//    public void setReservas(Set reservas) {
//        this.reservas = reservas;
//    }
//
//@OneToMany(fetch=FetchType.LAZY, mappedBy="publicacion")
//    public Set getPrestamos() {
//        return this.prestamos;
//    }
//    
//    public void setPrestamos(Set prestamos) {
//        this.prestamos = prestamos;
//    }




}


