package com.santiago.biblioteca.bean;
// Generated 06/11/2013 04:56:16 AM by Hibernate Tools 3.6.0

import java.util.HashSet;
import java.util.Set;
import javax.persistence.Column;
import javax.persistence.Entity;
import javax.persistence.GeneratedValue;
import static javax.persistence.GenerationType.IDENTITY;
import javax.persistence.Id;
import javax.persistence.Table;
import org.springframework.format.annotation.NumberFormat;

/**
 * Tipopublicacion generated by hbm2java
 */
@Entity
@Table(name = "tipopublicacion", catalog = "biblioteca"
)
public class Tipopublicacion implements java.io.Serializable {

    @NumberFormat(style = NumberFormat.Style.NUMBER)
    private int id;
    private String descripcion;
    private Set publicacions = new HashSet(0);

    public Tipopublicacion() {
    }

    public Tipopublicacion(int id) {
        this.id = id;
    }

    public Tipopublicacion(int id, String descripcion, Set publicacions) {
        this.id = id;
        this.descripcion = descripcion;
        this.publicacions = publicacions;
    }

    @Id
    @GeneratedValue(strategy = IDENTITY)

    @Column(name = "id", unique = true, nullable = false)
    public int getId() {
        return this.id;
    }

    public void setId(int id) {
        this.id = id;
    }

    @Column(name = "descripcion", length = 45)
    public String getDescripcion() {
        return this.descripcion;
    }

    public void setDescripcion(String descripcion) {
        this.descripcion = descripcion;
    }

//
//@OneToMany(fetch=FetchType.LAZY, mappedBy="tipopublicacion")
//    public Set getPublicacions() {
//        return this.publicacions;
//    }
//    
//    public void setPublicacions(Set publicacions) {
//        this.publicacions = publicacions;
//    }
//
    @Override
    public String toString() {
        return "Tipopublicacion{" + "descripcion=" + descripcion + '}';
    }

    @Override
    public int hashCode() {
        int hash = 3;
        hash = 11 * hash + this.id;
        return hash;
    }

    @Override
    public boolean equals(Object obj) {
        if (obj == null) {
            return false;
        }
        if (getClass() != obj.getClass()) {
            return false;
        }
        final Tipopublicacion other = (Tipopublicacion) obj;
        if (this.id != other.id) {
            return false;
        }
        return true;
    }

}
