package com.santiago.biblioteca.bean;
// Generated 06/11/2013 04:56:16 AM by Hibernate Tools 3.6.0


import java.util.HashSet;
import java.util.Set;
import javax.persistence.Column;
import javax.persistence.Entity;
import javax.persistence.FetchType;
import javax.persistence.Id;
import javax.persistence.OneToMany;
import javax.persistence.Table;

/**
 * Tipopublicacion generated by hbm2java
 */
@Entity
@Table(name="tipopublicacion"
    ,catalog="biblioteca"
)
public class Tipopublicacion  implements java.io.Serializable {


     private int id;
     private String descripcion;
     private Set publicacions = new HashSet(0);

    public Tipopublicacion() {
    }

	
    public Tipopublicacion(int id) {
        this.id = id;
    }
    public Tipopublicacion(int id, String descripcion, Set publicacions) {
       this.id = id;
       this.descripcion = descripcion;
       this.publicacions = publicacions;
    }
   
     @Id 

    
    @Column(name="id", unique=true, nullable=false)
    public int getId() {
        return this.id;
    }
    
    public void setId(int id) {
        this.id = id;
    }

    
    @Column(name="descripcion", length=45)
    public String getDescripcion() {
        return this.descripcion;
    }
    
    public void setDescripcion(String descripcion) {
        this.descripcion = descripcion;
    }
//
//@OneToMany(fetch=FetchType.LAZY, mappedBy="tipopublicacion")
//    public Set getPublicacions() {
//        return this.publicacions;
//    }
//    
//    public void setPublicacions(Set publicacions) {
//        this.publicacions = publicacions;
//    }
//



}


