package com.santiago.biblioteca.bean;
// Generated 06/11/2013 04:56:16 AM by Hibernate Tools 3.6.0


import java.util.HashSet;
import java.util.Set;
import javax.persistence.Column;
import javax.persistence.Entity;
import javax.persistence.FetchType;
import javax.persistence.Id;
import javax.persistence.JoinColumn;
import javax.persistence.ManyToOne;
import javax.persistence.OneToMany;
import javax.persistence.Table;
import javax.persistence.UniqueConstraint;

/**
 * Usuario generated by hbm2java
 */
@Entity
@Table(name="usuario"
    ,catalog="biblioteca"
    , uniqueConstraints = @UniqueConstraint(columnNames="dni") 
)
public class Usuario  implements java.io.Serializable {


     private int id;
     private Tipousuario tipousuario;
     private String dni;
     private String password;
     private String nombres;
     private String apellidos;
     private String telefono;
     private String direccion;
     private Set prestamos = new HashSet(0);
     private Set reservas = new HashSet(0);

    public Usuario() {
    }

	
    public Usuario(int id, Tipousuario tipousuario) {
        this.id = id;
        this.tipousuario = tipousuario;
    }
    public Usuario(int id, Tipousuario tipousuario, String dni, String password, String nombres, String apellidos, String telefono, String direccion, Set prestamos, Set reservas) {
       this.id = id;
       this.tipousuario = tipousuario;
       this.dni = dni;
       this.password = password;
       this.nombres = nombres;
       this.apellidos = apellidos;
       this.telefono = telefono;
       this.direccion = direccion;
       this.prestamos = prestamos;
       this.reservas = reservas;
    }
   
     @Id 

    
    @Column(name="id", unique=true, nullable=false)
    public int getId() {
        return this.id;
    }
    
    public void setId(int id) {
        this.id = id;
    }

@ManyToOne(fetch=FetchType.LAZY)
    @JoinColumn(name="tipousuario_id", nullable=false)
    public Tipousuario getTipousuario() {
        return this.tipousuario;
    }
    
    public void setTipousuario(Tipousuario tipousuario) {
        this.tipousuario = tipousuario;
    }

    
    @Column(name="dni", unique=true, length=8)
    public String getDni() {
        return this.dni;
    }
    
    public void setDni(String dni) {
        this.dni = dni;
    }

    
    @Column(name="password", length=100)
    public String getPassword() {
        return this.password;
    }
    
    public void setPassword(String password) {
        this.password = password;
    }

    
    @Column(name="nombres", length=45)
    public String getNombres() {
        return this.nombres;
    }
    
    public void setNombres(String nombres) {
        this.nombres = nombres;
    }

    
    @Column(name="apellidos", length=45)
    public String getApellidos() {
        return this.apellidos;
    }
    
    public void setApellidos(String apellidos) {
        this.apellidos = apellidos;
    }

    
    @Column(name="telefono", length=45)
    public String getTelefono() {
        return this.telefono;
    }
    
    public void setTelefono(String telefono) {
        this.telefono = telefono;
    }

    
    @Column(name="direccion", length=45)
    public String getDireccion() {
        return this.direccion;
    }
    
    public void setDireccion(String direccion) {
        this.direccion = direccion;
    }

@OneToMany(fetch=FetchType.LAZY, mappedBy="usuario")
    public Set getPrestamos() {
        return this.prestamos;
    }
    
    public void setPrestamos(Set prestamos) {
        this.prestamos = prestamos;
    }

@OneToMany(fetch=FetchType.LAZY, mappedBy="usuario")
    public Set getReservas() {
        return this.reservas;
    }
    
    public void setReservas(Set reservas) {
        this.reservas = reservas;
    }




}


